import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import 'normalize.css';
import "@/styles/globals.scss";
import ReduxProvider from "@/store/provider";
import NavBar from "@/components/nav-bar";
import Footer from '@/components/footer'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <AntdRegistry>
              <ReduxProvider>
                  <header>
                      <NavBar></NavBar>
                  </header>
                  <main>
                      {children}
                  </main>
                  <footer>
                      <Footer />
                  </footer>
              </ReduxProvider>
          </AntdRegistry>
      </body>
    </html>
  );
}
